Dz9
Cpr4z/2022-2-VK-EDU-FS-Frontend-M-Agarkov pull request #14
Opened 2022-12-10 22:29 UTC by Cpr4z

# Домашнее задание №9

Прошу @martinkomitsky или @haseprogram проверить его.

Что было сделано:
*Добавлены редьюсеры (для текущего чата, сообщений) и хранилище

2022-12-16 21:37 UTC, HaseProgram requested changes
Все неплохо, но давай избавимся от редюсера ``ActiveChat``, достаточно будет передавать ID через url. Если есть необходимость хранить название, описание и автора, то лучше завести стейт в виде массива таких чатов и доставать их оттуда.

2022-12-16 21:37 UTC, HaseProgram commented on react-chat/src/reducers/viewReduser.js
> +    isDesktop: true,
Зачем заводить сразу 2 флага? Одного мне кажется вполне достаточно

2022-12-17 09:48 UTC, Cpr4z commented on react-chat/src/reducers/viewReduser.js
> +    isDesktop: true,
Исправил.

2022-12-17 09:50 UTC, Cpr4z commented
> Все неплохо, но давай избавимся от редюсера `ActiveChat`, достаточно будет передавать ID через url. Если есть необходимость хранить название, описание и автора, то лучше завести стейт в виде массива таких чатов и доставать их оттуда.



> Все неплохо, но давай избавимся от редюсера `ActiveChat`, достаточно будет передавать ID через url. Если есть необходимость хранить название, описание и автора, то лучше завести стейт в виде массива таких чатов и доставать их оттуда.



> 

А почему плохо использовать редьюсер для активного чата?...

2022-12-17 10:08 UTC, Cpr4z commented
> Все неплохо, но давай избавимся от редюсера `ActiveChat`, достаточно будет передавать ID через url. Если есть необходимость хранить название, описание и автора, то лучше завести стейт в виде массива таких чатов и доставать их оттуда.

Просто мне придется откатиться на предыдущую версию проекта, а так я попробовал ввести какой-то новый функционал что ли

2022-12-17 13:17 UTC, HaseProgram commented
> А почему плохо использовать редьюсер для активного чата?...

Потому что это не та информация, которую стоит хранить в сторе) На лекции по редаксу мы проговаривали момент, что не стоит всю информацию хранить в глобальном стойте. Активный чат как раз можно хранить в стейте страницы. Если нужно брать информацию о нем из апишки (стора), тогда, как я сказал, лучше завести стейт в виде массива этих чатов с информацией.

2022-12-17 13:19 UTC, HaseProgram commented
> Просто мне придется откатиться на предыдущую версию проекта, а так я попробовал ввести какой-то новый функционал что ли

А что значит "откатываться"? У тебя есть ветка с несмерженным дз, в ней и продолжай разработку)

2022-12-17 15:33 UTC, Cpr4z commented
> Все неплохо, но давай избавимся от редюсера `ActiveChat`, достаточно будет передавать ID через url. Если есть необходимость хранить название, описание и автора, то лучше завести стейт в виде массива таких чатов и доставать их оттуда.

вроде убрал.

2022-12-21 10:40 UTC, HaseProgram commented on react-chat/src/Components/SidebarBody/SidebarBody.jsx
> +function SidebarBody(props, {openChat}) {
А что такое openChat? Откуда она передается и что делает?

2022-12-21 11:11 UTC, Cpr4z commented on react-chat/src/Components/SidebarBody/SidebarBody.jsx
> +function SidebarBody(props, {openChat}) {
Функция открывающая чат, передаю ее в качестве параметра openChat компоненту SidebarBody

2022-12-21 11:28 UTC, HaseProgram commented on react-chat/src/Components/SidebarBody/SidebarBody.jsx
> +function SidebarBody(props, {openChat}) {
Можешь написать файл и строку, где она передается?
А также файл и строку, где определена сама функция

2022-12-21 11:31 UTC, Cpr4z commented on react-chat/src/Components/SidebarBody/SidebarBody.jsx
> +function SidebarBody(props, {openChat}) {
App.js 21 строка и 60 строка

2022-12-21 11:44 UTC, HaseProgram commented on react-chat/src/Components/SidebarBody/SidebarBody.jsx
> +function SidebarBody(props, {openChat}) {
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/5223992/208897656-99ccfb33-6a07-4174-8b20-24a9185f2581.png">

Вот App.js 21 и 60 строки. Не нашел :(

2022-12-21 11:47 UTC, Cpr4z commented on react-chat/src/Components/SidebarBody/SidebarBody.jsx
> +function SidebarBody(props, {openChat}) {
Я смотрел в ветке 8 дз,сори.
Ща добавлю

2022-12-21 11:52 UTC, HaseProgram commented on react-chat/src/Components/SidebarBody/SidebarBody.jsx
> +function SidebarBody(props, {openChat}) {
Подожди, а зачем вообще она нужна? Ты ее удалил и правильно сделал. У тебя же есть роутер, пусть он всю задачу и выполняет. Он в адресной строке передает id чата, на его основе и показывай нужный контент...

2022-12-21 15:35 UTC, Cpr4z commented on react-chat/src/Components/SidebarBody/SidebarBody.jsx
> +function SidebarBody(props, {openChat}) {
Да, логично. Убрал.

2022-12-26 07:57 UTC, HaseProgram requested changes, later dismissed
Проект, кажется, не запускался после правок) Все еще есть ошибки, которые должны быть видны при отладке) Например, в компоненте ChatBody, надо исправлять)

2022-12-30 14:09 UTC, martinkomitsky approved these changes
7

2022-12-30 14:10 UTC, merged